import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import dataPool from '../data/sit-data-pool.json'
import type { SITVariantType } from '../types'

// ─── Types ───────────────────────────────────────────────────────────────────
interface TestResult {
  testId: string
  sitName: string
  variant: SITVariantType
  variantKey: string
  occurrences: number
  expectedLabel: 'Confidentiel' | 'Secret'
  status: 'Passed' | 'Failed' | 'Pending'
  date: string | null
}

// ─── All test cases (global) ─────────────────────────────────────────────────
const TEST_CASES: Omit<TestResult, 'status' | 'date'>[] = [
  { testId: 'F-IBAN-Aplus', sitName: 'IBAN', variant: 'A+', variantKey: 'Aplus', occurrences: 5,  expectedLabel: 'Confidentiel' },
  { testId: 'F-IBAN-B',    sitName: 'IBAN', variant: 'B',  variantKey: 'B',     occurrences: 10, expectedLabel: 'Secret' },
  { testId: 'F-CC-Aplus',  sitName: 'Credit Card', variant: 'A+', variantKey: 'Aplus', occurrences: 5,  expectedLabel: 'Confidentiel' },
  { testId: 'F-CC-B',      sitName: 'Credit Card', variant: 'B',  variantKey: 'B',     occurrences: 10, expectedLabel: 'Secret' },
  { testId: 'F-DC-Aplus',  sitName: 'EU Debit Card', variant: 'A+', variantKey: 'Aplus', occurrences: 5,  expectedLabel: 'Confidentiel' },
  { testId: 'F-DC-B',      sitName: 'EU Debit Card', variant: 'B',  variantKey: 'B',     occurrences: 10, expectedLabel: 'Secret' },
  { testId: 'F-SW-Aplus',  sitName: 'SWIFT Code', variant: 'A+', variantKey: 'Aplus', occurrences: 5,  expectedLabel: 'Confidentiel' },
  { testId: 'F-SW-B',      sitName: 'SWIFT Code', variant: 'B',  variantKey: 'B',     occurrences: 10, expectedLabel: 'Secret' },
  { testId: 'F-ABA-Aplus',  sitName: 'ABA Routing', variant: 'A+', variantKey: 'Aplus', occurrences: 5,  expectedLabel: 'Confidentiel' },
  { testId: 'F-ABA-B',     sitName: 'ABA Routing', variant: 'B',  variantKey: 'B',     occurrences: 10, expectedLabel: 'Secret' },
]

// ─── SIT ID → purview_detection_rules key mapping ───────────────────────────
const SIT_RULES_KEY: Record<string, keyof typeof dataPool.purview_detection_rules> = {
  'iban': 'iban',
  'credit-card': 'credit_card',
  'eu-debit-card': 'eu_debit_card',
  'swift-code': 'swift',
  'aba-routing': 'aba',
}

// ─── Helpers ─────────────────────────────────────────────────────────────────
function readResultFromStorage(testId: string): { status: 'Passed' | 'Failed' | 'Pending'; date: string | null } {
  const raw = localStorage.getItem(`sit-result-${testId}`)
  const parsed = raw ? JSON.parse(raw) : null
  return {
    status: parsed?.status ?? 'Pending',
    date: parsed?.date ?? null,
  }
}

function readAllResults(): TestResult[] {
  return TEST_CASES.map(tc => {
    const { status, date } = readResultFromStorage(tc.testId)
    return { ...tc, status, date }
  })
}

async function loadLogoBase64(): Promise<string> {
  const blob = await (await fetch('/axa.png')).blob()
  return new Promise((resolve, reject) => {
    const r = new FileReader()
    r.onloadend = () => resolve(r.result as string)
    r.onerror = reject
    r.readAsDataURL(blob)
  })
}

function sanitizeFilename(name: string): string {
  return name.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-]/g, '')
}

// ─── Shared PDF base builder ──────────────────────────────────────────────────
function buildSharedBase(language: 'fr' | 'en', logo: string, titleOverride?: string) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // Constants
  const W = 210
  const MARGIN = 16
  const CW = W - MARGIN * 2
  const AXA_BLUE = '#0033A0'
  const AXA_RED = '#DA291C'
  const DARK = '#222222'
  const SUBTLE = '#666666'
  const LIGHT_BG = '#F5F7FA'
  const BORDER = '#E5E7EB'
  const ALT_ROW = '#F9FAFB'
  const HDR_H = 18

  const today = new Date().toLocaleDateString(
    language === 'fr' ? 'fr-FR' : 'en-GB',
    { year: 'numeric', month: 'long', day: 'numeric' }
  )

  const L = {
    title: titleOverride ?? (language === 'fr' ? 'Rapport de Test — Auto-Labeling CM16' : 'Test Report — Auto-Labeling CM16'),
    project: language === 'fr' ? 'Projet' : 'Project',
    milestone: language === 'fr' ? 'Jalon' : 'Milestone',
    env: language === 'fr' ? 'Environnement' : 'Environment',
    genBy: language === 'fr' ? 'Généré par' : 'Generated by',
    genOn: language === 'fr' ? 'Date de gén.' : 'Report Date',
    summary: language === 'fr' ? 'Résumé Exécutif' : 'Executive Summary',
    total: language === 'fr' ? 'Total' : 'Total',
    passed: language === 'fr' ? 'Réussis' : 'Passed',
    failed: language === 'fr' ? 'Échoués' : 'Failed',
    pending: language === 'fr' ? 'En attente' : 'Pending',
    overall: language === 'fr' ? 'Statut global' : 'Overall Status',
    results: language === 'fr' ? 'Résultats des Tests' : 'Test Results',
    testId: language === 'fr' ? 'ID Test' : 'Test ID',
    sitType: language === 'fr' ? 'Type SIT' : 'SIT Type',
    variant: language === 'fr' ? 'Variante' : 'Variant',
    occs: language === 'fr' ? 'Occurrences' : 'Occurrences',
    expected: language === 'fr' ? 'Label Attendu' : 'Expected Label',
    status: language === 'fr' ? 'Statut' : 'Status',
    date: language === 'fr' ? 'Date' : 'Date',
    footer: language === 'fr' ? 'AXA — Usage Interne Uniquement — Confidentiel' : 'AXA — Internal Use Only — Confidential',
    allPass: language === 'fr' ? 'Validé' : 'Passed',
    actNeeded: language === 'fr' ? 'Action Requise' : 'Action Required',
    inProgress: language === 'fr' ? 'En Cours' : 'In Progress',
    // SIT details block
    sitDetails: language === 'fr' ? 'Informations du Test' : 'Test Information',
    sitName: language === 'fr' ? 'Nom du SIT' : 'SIT Name',
    detectionScope: language === 'fr' ? 'Portée de détection' : 'Detection Scope',
    confidence: language === 'fr' ? 'Niveau de confiance' : 'Confidence Level',
    occurrenceRule: language === 'fr' ? 'Règle d\'occurrence' : 'Occurrence Rule',
    source: language === 'fr' ? 'Source' : 'Source',
    variantARuleText: language === 'fr'
      ? 'Variante A  : 1 occurrence  → Confidentiel'
      : 'Variant A   : 1 occurrence  → Confidentiel',
    variantAPlusRuleText: language === 'fr'
      ? 'Variante A+ : 5 occurrences → Confidentiel'
      : 'Variant A+  : 5 occurrences → Confidentiel',
    variantBRuleText: language === 'fr'
      ? 'Variante B  : 10 occurrences → Secret'
      : 'Variant B   : 10 occurrences → Secret',
    sourceValue: 'AXA Auto-Labelling Request-Form Template V1.1',
  }

  const drawHeader = () => {
    doc.setFillColor('#FFFFFF')
    doc.rect(0, 0, W, HDR_H, 'F')
    doc.addImage(logo, 'PNG', MARGIN, 4, 22, 9)

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.setTextColor(AXA_BLUE)
    doc.text(L.title, MARGIN + 28, HDR_H / 2 + 2, { align: 'left' })

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(SUBTLE)
    doc.text(today, W - MARGIN, HDR_H / 2 + 1, { align: 'right' })

    // Bottom accent line
    doc.setFillColor(AXA_BLUE)
    doc.rect(0, HDR_H - 0.5, W, 0.5, 'F')
  }

  const drawFooter = (page: number, total: number) => {
    const fY = 287
    doc.setDrawColor(BORDER)
    doc.setLineWidth(0.3)
    doc.line(MARGIN, fY - 3, W - MARGIN, fY - 3)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor('#9CA3AF')
    doc.text(L.footer, MARGIN, fY + 2, { align: 'left' })
    doc.text(`${page} / ${total}`, W - MARGIN, fY + 2, { align: 'right' })
  }

  const drawProjectInfo = (startY: number): number => {
    const y = startY
    const infoRows = [
      [L.project, 'OneTrust — AXA'],
      [L.milestone, 'CM16 — Financial SITs Validation'],
      [L.env, 'Microsoft Purview — Auto-Labeling'],
      [L.genBy, 'AXA DLP Team']
    ]

    doc.setFillColor(LIGHT_BG)
    doc.roundedRect(MARGIN, y, CW, 30, 2, 2, 'F')
    doc.setDrawColor(BORDER)
    doc.setLineWidth(0.2)
    doc.roundedRect(MARGIN, y, CW, 30, 2, 2, 'S')

    let rowY = y + 7
    const COL_LABEL_1 = MARGIN + 6
    const COL_VALUE_1 = MARGIN + 40
    const COL_LABEL_2 = MARGIN + 90
    const COL_VALUE_2 = MARGIN + 120

    infoRows.slice(0, 2).forEach(([label, value]) => {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(SUBTLE)
      doc.text(label, COL_LABEL_1, rowY)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(DARK)
      doc.text(value, COL_VALUE_1, rowY)
      rowY += 10
    })

    rowY = y + 7
    infoRows.slice(2, 4).forEach(([label, value]) => {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(SUBTLE)
      doc.text(label, COL_LABEL_2, rowY)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(DARK)
      doc.text(value, COL_VALUE_2, rowY)
      rowY += 10
    })

    return y + 36
  }

  const drawSectionTitle = (title: string, y: number): number => {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(AXA_BLUE)
    doc.text(title, MARGIN, y)
    y += 3
    doc.setDrawColor(BORDER)
    doc.setLineWidth(0.5)
    doc.line(MARGIN, y, W - MARGIN, y)
    return y + 6
  }

  const tableStyles = {
    headStyles: {
      fillColor: AXA_BLUE,
      textColor: '#FFFFFF',
      fontStyle: 'bold' as const,
      fontSize: 9,
      halign: 'center' as const,
      lineWidth: 0,
    },
    bodyStyles: {
      fontSize: 9,
      textColor: DARK,
      halign: 'center' as const,
      lineColor: BORDER,
      lineWidth: { bottom: 0.1 },
    },
    alternateRowStyles: { fillColor: ALT_ROW },
    tableLineColor: BORDER,
    tableLineWidth: 0.1,
    didParseCell: (data: Parameters<NonNullable<Parameters<typeof autoTable>[1]['didParseCell']>>[0]) => {
      if (data.section !== 'body') return
      if (data.column.index === 5) { // Status column
        const s = data.cell.raw as string
        if (s === 'Passed') { data.cell.styles.textColor = '#166534'; data.cell.styles.fontStyle = 'bold' }
        else if (s === 'Failed') { data.cell.styles.textColor = AXA_RED; data.cell.styles.fontStyle = 'bold' }
        else { data.cell.styles.textColor = '#D97706'; data.cell.styles.fontStyle = 'normal' }
      }
      if (data.column.index === 4) { // Expected Label column
        const l = data.cell.raw as string
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = l === 'Secret' ? AXA_RED : '#1E40AF'
      }
    },
  }

  return { doc, W, MARGIN, CW, AXA_BLUE, AXA_RED, DARK, SUBTLE, LIGHT_BG, BORDER, ALT_ROW, HDR_H, today, L, drawHeader, drawFooter, drawProjectInfo, drawSectionTitle, tableStyles }
}

// ─── Individual SIT Report ────────────────────────────────────────────────────
export async function exportSITReport(
  sitId: string,
  sitName: string,
  purviewDescription: string,
  confidenceLevel: string,
  language: 'fr' | 'en'
): Promise<void> {
  const logo = await loadLogoBase64()
  const titleOverride = language === 'fr'
    ? `Rapport de Test — ${sitName}`
    : `Test Report — ${sitName}`

  const { doc, MARGIN, DARK, SUBTLE, HDR_H, L, drawHeader, drawFooter, drawProjectInfo, drawSectionTitle, tableStyles } =
    buildSharedBase(language, logo, titleOverride)

  const prefixMap: Record<string, string> = {
    'iban': 'F-IBAN',
    'credit-card': 'F-CC',
    'eu-debit-card': 'F-DC',
    'swift-code': 'F-SW',
    'aba-routing': 'F-ABA',
  }
  const sitTestCases = TEST_CASES.filter(tc =>
    tc.testId.startsWith(prefixMap[sitId] ?? '')
  )

  const results: TestResult[] = sitTestCases.map(tc => {
    const { status, date } = readResultFromStorage(tc.testId)
    return { ...tc, status, date }
  })

  const rulesKey = SIT_RULES_KEY[sitId]
  const rules = rulesKey ? dataPool.purview_detection_rules[rulesKey] : null

  drawHeader()
  let y = HDR_H + 8

  y = drawProjectInfo(y)
  y += 6

  // SIT Details Section
  y = drawSectionTitle(L.sitDetails, y)

  const detailRows = [
    [L.sitName, rules?.sit_name ?? sitName],
    [L.detectionScope, purviewDescription || (rules?.detection_scope ?? '—')],
    [L.confidence, confidenceLevel || (rules?.confidence ?? '—')],
    [L.occurrenceRule, L.variantARuleText],
    ['', L.variantAPlusRuleText],
    ['', L.variantBRuleText],
    [L.source, L.sourceValue],
  ]

  const COL_LABEL = MARGIN
  const COL_VALUE = MARGIN + 55
  detailRows.forEach(([label, value]) => {
    if (label) {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(SUBTLE)
      doc.text(label, COL_LABEL, y)
    }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(DARK)
    doc.text(value, COL_VALUE, y)
    y += 7
  })

  y += 8

  // Results Table
  y = drawSectionTitle(L.results, y)

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [[L.testId, L.sitType, L.variant, L.occs, L.expected, L.status, L.date]],
    body: results.map(r => [
      r.testId,
      r.sitName,
      r.variant,
      String(r.occurrences),
      r.expectedLabel,
      r.status,
      r.date ?? '—',
    ]),
    ...tableStyles,
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 22 },
      1: { cellWidth: 32 },
      2: { cellWidth: 18 },
      3: { cellWidth: 24 },
      4: { cellWidth: 28 },
      5: { cellWidth: 24 },
      6: { cellWidth: 30 },
    },
    didDrawPage: () => {
      const pn = doc.getCurrentPageInfo().pageNumber
      drawFooter(pn, doc.getNumberOfPages())
    },
  })

  drawFooter(1, doc.getNumberOfPages())

  const safeName = sanitizeFilename(sitName)
  const filename = language === 'fr'
    ? `AXA_Rapport_${safeName}_CM16_${Date.now()}.pdf`
    : `AXA_Report_${safeName}_CM16_${Date.now()}.pdf`
  doc.save(filename)
}

// ─── Global Report ────────────────────────────────────────────────────────────
export async function exportGlobalReport(language: 'fr' | 'en'): Promise<void> {
  const results = readAllResults()
  const logo = await loadLogoBase64()

  const { doc, MARGIN, CW, AXA_BLUE, AXA_RED, DARK, SUBTLE, BORDER, HDR_H, L, drawHeader, drawFooter, drawProjectInfo, drawSectionTitle, tableStyles } =
    buildSharedBase(language, logo)

  const passed = results.filter(r => r.status === 'Passed').length
  const failed = results.filter(r => r.status === 'Failed').length
  const pending = results.filter(r => r.status === 'Pending').length

  const overallLabel = failed > 0 ? L.actNeeded : pending > 0 ? L.inProgress : L.allPass
  const overallColor = failed > 0 ? AXA_RED : pending > 0 ? '#D97706' : '#166534'
  const overallBgColor = failed > 0 ? '#FEF2F2' : pending > 0 ? '#FFFBEB' : '#F0FDF4'

  drawHeader()
  let y = HDR_H + 8

  y = drawProjectInfo(y)
  y += 6

  // Executive Summary section
  y = drawSectionTitle(L.summary, y)

  const cardW = (CW - 12) / 4
  const stats = [
    { label: L.total, value: String(results.length), color: AXA_BLUE },
    { label: L.passed, value: String(passed), color: '#166534' },
    { label: L.failed, value: String(failed), color: AXA_RED },
    { label: L.pending, value: String(pending), color: '#D97706' },
  ]

  let cardX = MARGIN
  const cardH = 22

  stats.forEach((s) => {
    // Draw Card Background
    doc.setFillColor('#FFFFFF')
    doc.roundedRect(cardX, y, cardW, cardH, 1, 1, 'F')

    doc.setDrawColor(BORDER)
    doc.setLineWidth(0.15)
    doc.roundedRect(cardX, y, cardW, cardH, 1, 1, 'S')

    // Colored Accent Strip on Left side
    doc.setFillColor(s.color)
    doc.rect(cardX, y, 1.5, cardH, 'F')

    // Inside Card content (Left Aligned for cleaner executive appeal)
    const pad = 6
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(SUBTLE)
    doc.text(s.label, cardX + pad, y + 7)

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(22)
    doc.setTextColor(s.color)
    doc.text(s.value, cardX + pad, y + 17)

    cardX += cardW + 4
  })

  y += cardH + 8

  // Overall Status Pill
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(DARK)
  doc.text(`${L.overall} : `, MARGIN, y + 4)

  const textWidth = doc.getTextWidth(overallLabel)
  const badgeStart = MARGIN + doc.getTextWidth(`${L.overall} : `) + 2

  doc.setFillColor(overallBgColor)
  doc.roundedRect(badgeStart, y - 1, textWidth + 8, 7, 3.5, 3.5, 'F')
  doc.setTextColor(overallColor)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text(overallLabel, badgeStart + 4, y + 3.8)

  y += 14

  // Results table
  y = drawSectionTitle(L.results, y)

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [[L.testId, L.sitType, L.variant, L.occs, L.expected, L.status, L.date]],
    body: results.map(r => [
      r.testId,
      r.sitName,
      r.variant,
      String(r.occurrences),
      r.expectedLabel,
      r.status,
      r.date ?? '—',
    ]),
    ...tableStyles,
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 22 },
      1: { cellWidth: 32 },
      2: { cellWidth: 18 },
      3: { cellWidth: 24 },
      4: { cellWidth: 28 },
      5: { cellWidth: 24 },
      6: { cellWidth: 30 },
    },
    didDrawPage: () => {
      const pn = doc.getCurrentPageInfo().pageNumber
      drawFooter(pn, doc.getNumberOfPages())
    },
  })

  drawFooter(1, doc.getNumberOfPages())
  const total = doc.getNumberOfPages()
  for (let p = 2; p <= total; p++) {
    doc.setPage(p)
    drawHeader()
  }

  const filename = language === 'fr'
    ? `AXA_Rapport_AutoLabeling_CM16_${Date.now()}.pdf`
    : `AXA_Test_Report_AutoLabeling_CM16_${Date.now()}.pdf`
  doc.save(filename)
}

// ─── Backward-compat alias ────────────────────────────────────────────────────
export const exportPDFReport = exportGlobalReport
